config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :user_journeys
  resources :journeys
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/journey.rb
class Journey < ApplicationRecord
	has_many :users, :through => :user_journeys
	has_many :user_journeys
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :user_journeys
  has_many :journeys, :through => :user_journeys
end

app/models/user_journey.rb
class UserJourney < ApplicationRecord
	belongs_to :user
	belongs_to :journey
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @journey = Journey.last
  end
end

app/controllers/journeys_controller.rb
class JourneysController < ApplicationController
  before_action :authenticate_user!
  before_action :set_journey, only: [:show, :edit, :update, :destroy]

  # GET /journeys
  # GET /journeys.json
  def index
    @journeys = current_user.journeys
    @journey = Journey.last
  end

  # GET /journeys/1
  # GET /journeys/1.json
  def show
  end

  # GET /journeys/new
  def new
    @journey = Journey.new
  end

  # GET /journeys/1/edit
  def edit
  end

  # POST /journeys
  # POST /journeys.json
  def create
    Journey.transaction do
      @journey = Journey.create(journey_params)
      UserJourney.create(
        user_id: current_user.id,
        journey_id: @journey.id
      )
    end
    respond_to do |format|
      if @journey.id
        format.html { redirect_to @journey, notice: 'Journey was successfully created.' }
        format.json { render :show, status: :created, location: @journey }
      else
        format.html { render :new }
        format.json { render json: @journey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /journeys/1
  # PATCH/PUT /journeys/1.json
  def update
    respond_to do |format|
      if @journey.update(journey_params)
        format.html { redirect_to @journey, notice: 'Journey was successfully updated.' }
        format.json { render :show, status: :ok, location: @journey }
      else
        format.html { render :edit }
        format.json { render json: @journey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journeys/1
  # DELETE /journeys/1.json
  def destroy
    @journey.destroy
    respond_to do |format|
      format.html { redirect_to journeys_url, notice: 'Journey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journey
      @journey = Journey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def journey_params
      params.require(:journey).permit(:start_address, :end_address)
    end
end

app/controllers/user_journeys_controller.rb
class UserJourneysController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user_journey, only: [:show, :edit, :update, :destroy]

  # GET /user_journeys
  # GET /user_journeys.json
  def index
    @user_journeys = UserJourney.all
  end

  # GET /user_journeys/1
  # GET /user_journeys/1.json
  def show
  end

  # GET /user_journeys/new
  def new
    @user_journey = UserJourney.new
  end

  # GET /user_journeys/1/edit
  def edit
  end

  # POST /user_journeys
  # POST /user_journeys.json
  def create
    @user_journey = UserJourney.new(user_journey_params)

    respond_to do |format|
      if @user_journey.save
        format.html { redirect_to @user_journey, notice: 'User journey was successfully created.' }
        format.json { render :show, status: :created, location: @user_journey }
      else
        format.html { render :new }
        format.json { render json: @user_journey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_journeys/1
  # PATCH/PUT /user_journeys/1.json
  def update
    respond_to do |format|
      if @user_journey.update(user_journey_params)
        format.html { redirect_to @user_journey, notice: 'User journey was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_journey }
      else
        format.html { render :edit }
        format.json { render json: @user_journey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_journeys/1
  # DELETE /user_journeys/1.json
  def destroy
    @user_journey.destroy
    respond_to do |format|
      format.html { redirect_to user_journeys_url, notice: 'User journey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_journey
      @user_journey = UserJourney.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_journey_params
      params.fetch(:user_journey, {})
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/journeys_helper.rb
module JourneysHelper
end

app/helpers/user_journeys_helper.rb
module UserJourneysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Get There Map</title>
    <meta name="viewport" content="initial-scale=1.0">
    <meta charset="utf-8">
  </head>
  <body>
    <form id="search">
      <div class="field_set">
        <label for="origin">Origin</label>
        <input id="origin" name="origin" value="NYC, NY" />
      </div>
      <div class="field_set">
        <label for="destination">Destination</label>
        <input id="destination" name="destination" value="San Diego, CA" />
      </div>
      <div class="field_set">
        <label for="mode">Mode</label>
        <select id="mode" name="mode">
          <option value="DRIVING">Driving</option>
          <option value="WALKING">Walking</option>
          <option value="TRANSIT">Transit</option>
          <option value="BICYCLING">Biking</option>
        </select>
      </div>
      <div class="field_set">
        <input type="submit" value="Search" />
      </div>
    </form>
    <div id="TimeDistance">
      <h4>Travel Time and Distance</h4>
      <h6 id="travelDistance"></h6>
      <h6 id="travelDuration"></h6>
    </div>
    <div id="map"></div>
    <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLEMAPSAPI'] %>"></script>
  </body>
</html>

app/views/journeys/_form.html.erb
<%= form_for(journey) do |f| %>
  <% if journey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(journey.errors.count, "error") %> prohibited this journey from being saved:</h2>

      <ul>
      <% journey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
    <%= f.label :start_address %><br>
    <%= f.text_field :start_address %>
  </div>
<div class="field">
    <%= f.label :end_address %><br>
    <%= f.text_field :end_address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/journeys/edit.html.erb
<h1>Editing Journey</h1>

<%= render 'form', journey: @journey %>

<%= link_to 'Show', @journey %> |
<%= link_to 'Back', journeys_path %>

app/views/journeys/index.html.erb
  <p id="notice"><%= notice %></p>

<h1>Journeys</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @journeys.each do |journey| %>
      <tr>
        <th><%= journey.start_address %></th>/
        <th> --> </th> 
        <th><%= journey.end_address %></th>
        <td><%= link_to 'Show', journey %></td>
        <td><%= link_to 'Edit', edit_journey_path(journey) %></td>
        <td><%= link_to 'Destroy', journey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

    <form id="search">
      <div class="field_set">
        <label for="origin">Origin</label>
        <input id="origin" name="origin" value="<%= @journey.start_address %>" />
      </div>
      <div class="field_set">
        <label for="destination">Destination</label>
        <input id="destination" name="destination" value="<%= @journey.end_address %>" />
      </div>
      <div class="field_set">
        <label for="mode">Mode</label>
        <select id="mode" name="mode">
          <option value="DRIVING">Driving</option>
          <option value="WALKING">Walking</option>
          <option value="TRANSIT">Transit</option>
          <option value="BICYCLING">Biking</option>
        </select>
      </div>
      <div class="field_set">
        <input type="submit" value="Search" />
      </div>
    </form>

    <div id="map"></div>

    <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLEMAPSAPI'] %>"></script>

app/views/journeys/new.html.erb
<h1>New Journey</h1>

<%= render 'form', journey: @journey %>

<%= link_to 'Back', journeys_path %>

app/views/journeys/show.html.erb
<p id="notice"><%= notice %></p>

<p>Start: <%= @journey.start_address %></p>
<p>End: <%= @journey.end_address %></p>

<%= link_to 'Edit', edit_journey_path(@journey) %> |
<%= link_to 'Back', journeys_path %>

app/views/layouts/_navbar.html.erb
<header>
  <div class="container-fluid"> 
  <div class="row">
     <div class="col-xs-12 banner">
          <nav id="nav" class="navbar navbar-default">
            <div class="container-fluid">
              
              <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-header">
                      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                      </button>
                      <a class="navbar-brand" href="#">
                        
                      </a>
              </div>
              
              <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                  <ul class="nav navbar-nav">
                        <li><%=link_to 'Travel Tips', root_path%></li> 
                        <%= content_tag :li do 
                          link_to "New Journey", new_journey_path
                          end if current_user %>
                        <%= content_tag :li do 
                          link_to "Old Journey", journeys_path
                          end if current_user %>
                        <%= content_tag :li do 
                          link_to "Logout", destroy_user_session_path, method: :delete
                          end if current_user %>
                        <%= content_tag :li do 
                          link_to "Login", new_user_session_url
                          end if !current_user %>
                        <%= content_tag :li do 
                        link_to "Register", new_user_registration_path 
                        end if !current_user %>     
                  </ul>
              </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
         </nav>
    </div>
  </div>
</div>    
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trip</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render 'layouts/navbar'%>
  	  <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/user_journeys/_form.html.erb
<%= form_for(user_journey) do |f| %>
  <% if user_journey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_journey.errors.count, "error") %> prohibited this user_journey from being saved:</h2>

      <ul>
      <% user_journey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_journeys/edit.html.erb
<h1>Editing User Journey</h1>

<%= render 'form', user_journey: @user_journey %>

<%= link_to 'Show', @user_journey %> |
<%= link_to 'Back', user_journeys_path %>

app/views/user_journeys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Journeys</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_journeys.each do |user_journey| %>
      <tr>
        <td><%= link_to 'Show', user_journey %></td>
        <td><%= link_to 'Edit', edit_user_journey_path(user_journey) %></td>
        <td><%= link_to 'Destroy', user_journey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Journey', new_user_journey_path %>

app/views/user_journeys/new.html.erb
<h1>New User Journey</h1>

<%= render 'form', user_journey: @user_journey %>

<%= link_to 'Back', user_journeys_path %>

app/views/user_journeys/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_journey_path(@user_journey) %> |
<%= link_to 'Back', user_journeys_path %>